name: Detect Push

on:
  push:
    branches:
      - main

jobs:
  detect-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show commit info
        run: |
          echo "Push detected on branch: ${{ github.ref }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Pushed by: ${{ github.actor }}"

      - name: List repo files
        run: ls -la
